language: java

jdk:
  - oraclejdk8

dist: trusty

addons:
  sonarcloud:
    organization: harveyhuizhang-github
    token:
      secure: 624cd10597a862c57608cfc61dbb7c484c7d68b0
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner