language: java

jdk:
  - oraclejdk8

dist: trusty

addons:
  sonarcloud:
    organization: harveyhuizhang-github
    token:
      secure: ${SONAR_TOKEN}
      
cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #624cd10597a862c57608cfc61dbb7c484c7d68b0
  #-Dsonar.profile=my_java_custom_rules
  #- mvn sonar:sonar -Dsonar.projectKey=HarveyHuiZhang_MyJenkinsDevOps -Dsonar.organization=harveyhuizhang-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}
  - mvn sonar:sonar -Dsonar.projectKey=HarveyHuiZhang_MyJenkinsDevOps -Dsonar.organization=harveyhuizhang-github -Dsonar.host.url=https://sonar.pwcinternal.com -Dsonar.login=9e0a7dacbe2dec55b9ce6673de7acd4ca78e81d2
